name: task_tracker
description: A simple task tracking app with Supabase integration
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^1.10.25
  provider: ^6.1.1
  flutter_dotenv: ^5.1.0
  flutter_slidable: ^3.0.1
  google_fonts: ^6.1.0
  loading_animation_widget: ^1.2.0+4
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env